#include "api/attention_causal_backward_api.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <vector>
static float score(std::vector<float> const& q, std::vector<float> const& k, std::uint32_t qi, std::uint32_t ki, std::uint32_t d) { float s = 0.0f; for (std::uint32_t c = 0; c < d; ++c) s += q[qi * d + c] * k[ki * d + c]; return s / std::sqrt(float(d)); }
static float weight(std::vector<float> const& q, std::vector<float> const& k, std::uint32_t qi, std::uint32_t ki, std::uint32_t d) { float maximum = -1e30f, normalizer = 0.0f; for (std::uint32_t i = 0; i <= qi; ++i) maximum = std::max(maximum, score(q, k, qi, i, d)); for (std::uint32_t i = 0; i <= qi; ++i) normalizer += std::exp(score(q, k, qi, i, d) - maximum); return std::exp(score(q, k, qi, ki, d) - maximum) / normalizer; }
int main() { constexpr std::uint32_t tokens = 3, d = 64; std::vector<float> q(tokens * d), k(tokens * d), v(tokens * d), dy(tokens * d), output(tokens * d), reference(tokens * d); for (std::size_t i = 0; i < q.size(); ++i) { q[i] = std::sin(float(i) * 0.07f); k[i] = std::cos(float(i) * 0.09f); v[i] = std::sin(float(i) * 0.11f); dy[i] = std::cos(float(i) * 0.13f); } float max_error = 0.0f; for (std::uint32_t mode = 0; mode < 3; ++mode) { std::fill(reference.begin(), reference.end(), 0.0f); for (std::uint32_t token = 0; token < tokens; ++token) for (std::uint32_t channel = 0; channel < d; ++channel) { if (mode == 0) { for (std::uint32_t key = 0; key <= token; ++key) { float dw = 0.0f, expected = 0.0f; for (std::uint32_t c = 0; c < d; ++c) dw += dy[token * d + c] * v[key * d + c]; for (std::uint32_t i = 0; i <= token; ++i) { float idw = 0.0f; for (std::uint32_t c = 0; c < d; ++c) idw += dy[token * d + c] * v[i * d + c]; expected += weight(q, k, token, i, d) * idw; } reference[token * d + channel] += weight(q, k, token, key, d) * (dw - expected) * k[key * d + channel] / std::sqrt(float(d)); } } else { for (std::uint32_t query = token; query < tokens; ++query) { float dw = 0.0f, expected = 0.0f; for (std::uint32_t c = 0; c < d; ++c) dw += dy[query * d + c] * v[token * d + c]; for (std::uint32_t i = 0; i <= query; ++i) { float idw = 0.0f; for (std::uint32_t c = 0; c < d; ++c) idw += dy[query * d + c] * v[i * d + c]; expected += weight(q, k, query, i, d) * idw; } reference[token * d + channel] += mode == 1 ? weight(q, k, query, token, d) * (dw - expected) * q[query * d + channel] / std::sqrt(float(d)) : weight(q, k, query, token, d) * dy[query * d + channel]; } } } if (spaceslug_attention_causal_backward(q.data(), k.data(), v.data(), dy.data(), output.data(), tokens, d, mode) != 0) return 1; for (std::size_t i = 0; i < output.size(); ++i) max_error = std::max(max_error, std::abs(output[i] - reference[i])); } if (max_error > 4e-4f) { std::cerr << "Attention backward mismatch: " << max_error << '\n'; return 1; } std::cout << "Attention backward: PASS max_abs_error=" << max_error << '\n'; }
