#include "core/vk_setup.h"
#include "embedded_shaders.hpp"
#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <stdexcept>
#include <vector>
namespace {
struct B { vk::Buffer b{}; VmaAllocation a{}; };
B make(vulkan_runtime::core::VulkanContext const& c, vk::DeviceSize n, vk::BufferUsageFlags u, VmaMemoryUsage m, VmaAllocationCreateFlags f=0) { VkBufferCreateInfo ci{}; ci.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO; ci.size=n; ci.usage=static_cast<VkBufferUsageFlags>(u); ci.sharingMode=VK_SHARING_MODE_EXCLUSIVE; VmaAllocationCreateInfo ai{}; ai.usage=m; ai.flags=f; VkBuffer b{}; VmaAllocation a{}; if(vmaCreateBuffer(c.allocator,&ci,&ai,&b,&a,nullptr)!=VK_SUCCESS) throw std::runtime_error("buffer"); return {vk::Buffer(b),a}; }
void destroy(vulkan_runtime::core::VulkanContext const& c,B& b){if(b.a)vmaDestroyBuffer(c.allocator,static_cast<VkBuffer>(b.b),b.a);b.a=nullptr;}
}
int main(){using namespace vulkan_runtime::core; constexpr uint32_t R=4,H=257; constexpr double eps=1e-5; auto c=create_context("rmsnorm-forward-state"); size_t n=size_t(R)*H, bytes=n*sizeof(float), gbytes=H*sizeof(float); std::vector<float>x(n),g(H),y(n),raw(n),inv(R),yref(n); const auto out0=bytes+gbytes, out1=out0+bytes, out2=out1+bytes, total=out2+R*sizeof(float); for(size_t i=0;i<n;++i)x[i]=.03f*float(int((i*17+3)%29)-14); for(uint32_t i=0;i<H;++i)g[i]=.6f+.003f*float(i%31); std::vector<double> iref(R); for(uint32_t r=0;r<R;++r){double ss=0;for(uint32_t j=0;j<H;++j){double z=x[r*H+j];ss+=z*z;}iref[r]=1/std::sqrt(ss/H+eps);for(uint32_t j=0;j<H;++j)yref[r*H+j]=float(double(x[r*H+j])*g[j]*iref[r]);}
 B bx=make(c,bytes,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),bg=make(c,gbytes,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),by=make(c,bytes,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferSrc,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),br=make(c,bytes,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferSrc,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),bi=make(c,R*sizeof(float),vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferSrc,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),st=make(c,total,vk::BufferUsageFlagBits::eTransferSrc|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_HOST,VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT);
 void*mp=nullptr;vmaMapMemory(c.allocator,st.a,&mp);auto*q=static_cast<uint8_t*>(mp);memcpy(q,x.data(),bytes);memcpy(q+bytes,g.data(),gbytes);vmaFlushAllocation(c.allocator,st.a,0,bytes+gbytes);vmaUnmapMemory(c.allocator,st.a);auto z=vulkan_runtime::shaders::get("rmsnorm_forward_state.spv");auto sm=c.device.createShaderModule(vk::ShaderModuleCreateInfo{}.setCodeSize(z.size).setPCode(reinterpret_cast<uint32_t const*>(z.data)));std::array<vk::DescriptorSetLayoutBinding,5>lb{};for(uint32_t i=0;i<5;++i)lb[i]=vk::DescriptorSetLayoutBinding{}.setBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setStageFlags(vk::ShaderStageFlagBits::eCompute);auto sl=c.device.createDescriptorSetLayout(vk::DescriptorSetLayoutCreateInfo{}.setBindings(lb));auto pl=c.device.createPipelineLayout(vk::PipelineLayoutCreateInfo{}.setSetLayouts(sl).setPushConstantRanges(vk::PushConstantRange{}.setStageFlags(vk::ShaderStageFlagBits::eCompute).setSize(8)));auto pr=c.device.createComputePipeline({},vk::ComputePipelineCreateInfo{}.setStage(vk::PipelineShaderStageCreateInfo{}.setStage(vk::ShaderStageFlagBits::eCompute).setModule(sm).setPName("main")).setLayout(pl));if(pr.result!=vk::Result::eSuccess)throw std::runtime_error("pipeline");auto pool=c.device.createDescriptorPool(vk::DescriptorPoolCreateInfo{}.setMaxSets(1).setPoolSizes(vk::DescriptorPoolSize{}.setType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(5)));auto ds=c.device.allocateDescriptorSets(vk::DescriptorSetAllocateInfo{}.setDescriptorPool(pool).setSetLayouts(sl)).front();std::array<vk::Buffer,5>bs{bx.b,bg.b,by.b,br.b,bi.b};std::array<vk::DescriptorBufferInfo,5>ii{};std::array<vk::WriteDescriptorSet,5>ww{};for(uint32_t i=0;i<5;++i){ii[i]=vk::DescriptorBufferInfo{}.setBuffer(bs[i]).setRange(VK_WHOLE_SIZE);ww[i]=vk::WriteDescriptorSet{}.setDstSet(ds).setDstBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setBufferInfo(ii[i]);}c.device.updateDescriptorSets(ww,{});
 auto cp=c.device.createCommandPool(vk::CommandPoolCreateInfo{}.setQueueFamilyIndex(c.computeQueueFamily));auto cmd=c.device.allocateCommandBuffers(vk::CommandBufferAllocateInfo{}.setCommandPool(cp).setLevel(vk::CommandBufferLevel::ePrimary).setCommandBufferCount(1)).front();cmd.begin(vk::CommandBufferBeginInfo{});cmd.copyBuffer(st.b,bx.b,vk::BufferCopy{}.setSize(bytes));cmd.copyBuffer(st.b,bg.b,vk::BufferCopy{}.setSrcOffset(bytes).setSize(gbytes));cmd.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer,vk::PipelineStageFlagBits::eComputeShader,{},vk::MemoryBarrier(vk::AccessFlagBits::eTransferWrite,vk::AccessFlagBits::eShaderRead),{},{});struct PC{uint32_t rows,hidden;}pc{R,H};cmd.bindPipeline(vk::PipelineBindPoint::eCompute,pr.value);cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute,pl,0,ds,{});cmd.pushConstants(pl,vk::ShaderStageFlagBits::eCompute,0,8,&pc);cmd.dispatch(R,1,1);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,vk::PipelineStageFlagBits::eTransfer,{},vk::MemoryBarrier(vk::AccessFlagBits::eShaderWrite,vk::AccessFlagBits::eTransferRead),{},{});cmd.copyBuffer(by.b,st.b,vk::BufferCopy{}.setDstOffset(out0).setSize(bytes));cmd.copyBuffer(br.b,st.b,vk::BufferCopy{}.setDstOffset(out1).setSize(bytes));cmd.copyBuffer(bi.b,st.b,vk::BufferCopy{}.setDstOffset(out2).setSize(R*sizeof(float)));cmd.end();c.computeQueue.submit(vk::SubmitInfo{}.setCommandBuffers(cmd));c.computeQueue.waitIdle();vmaMapMemory(c.allocator,st.a,&mp);vmaInvalidateAllocation(c.allocator,st.a,out0,bytes+bytes+R*sizeof(float));q=static_cast<uint8_t*>(mp);memcpy(y.data(),q+out0,bytes);memcpy(raw.data(),q+out1,bytes);memcpy(inv.data(),q+out2,R*sizeof(float));vmaUnmapMemory(c.allocator,st.a);double my=0,mi=0,mr=0;for(size_t i=0;i<n;++i){my=std::max(my,std::abs(double(y[i])-yref[i]));mr=std::max(mr,std::abs(double(raw[i])-x[i]));}for(uint32_t r=0;r<R;++r)mi=std::max(mi,std::abs(double(inv[r])-iref[r]));if(my>2e-4||mr!=0||mi>2e-5){std::cerr<<"RMSNorm forward-state mismatch y="<<my<<" raw="<<mr<<" inv="<<mi<<"\n";return 1;}std::cout<<"RMSNorm forward state: PASS max_y_error="<<my<<" max_inv_error="<<mi<<" raw_exact=1\n";destroy(c,bx);destroy(c,bg);destroy(c,by);destroy(c,br);destroy(c,bi);destroy(c,st);c.device.destroyCommandPool(cp);return 0;}
