# embed_shaders_impl.cmake — CMake script mode (cmake -P).
#
# Emits a C++ header that embeds one or more SPIR-V blobs as uint8_t arrays and
# exposes them through vulkan_runtime::shaders::get("<name>.spv").
#
# Invoked by ShaderToolchain.cmake's embed_shaders() as:
#
#     cmake -DOUTPUT=<path/to/embedded_shaders.hpp>
#           -DSHADER_NAMES=<name1>;<name2>;...
#           -DSHADER_FILES=<path1>;<path2>;...
#           -P embed_shaders_impl.cmake

if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_shaders_impl.cmake: OUTPUT is required")
endif()

set(text "")
string(APPEND text "// Auto-generated by embed_shaders(). Do not edit.\n")
string(APPEND text "#pragma once\n\n")
string(APPEND text "#include <cstdint>\n")
string(APPEND text "#include <cstddef>\n")
string(APPEND text "#include <string_view>\n\n")
string(APPEND text "namespace vulkan_runtime::shaders {\n\n")

set(registry "")

list(LENGTH SHADER_FILES n)
if(n EQUAL 0)
    message(FATAL_ERROR "embed_shaders_impl.cmake: SHADER_FILES is empty")
endif()

math(EXPR last "${n} - 1")
foreach(i RANGE 0 ${last})
    list(GET SHADER_FILES ${i} spv_file)
    list(GET SHADER_NAMES ${i} shader_name)
    get_filename_component(spv_base "${spv_file}" NAME)

    # Sanitize to a C++ identifier: strip the extension, then map any
    # non-alphanumeric character to '_'.
    string(REGEX REPLACE "\\.[^.]*$" "" base "${spv_base}")
    string(REGEX REPLACE "[^a-zA-Z0-9_]" "_" ident "${base}")

    file(READ "${spv_file}" raw HEX)
    string(LENGTH "${raw}" hex_len)
    math(EXPR byte_count "${hex_len} / 2")

    string(APPEND text "inline constexpr std::uint8_t k_${ident}[] = {\n")
    set(col 0)
    math(EXPR byte_last "${byte_count} - 1")
    foreach(b RANGE 0 ${byte_last})
        math(EXPR off "${b} * 2")
        string(SUBSTRING "${raw}" ${off} 2 hx)
        string(APPEND text "0x${hx},")
        math(EXPR col_next "${col} + 1")
        set(col "${col_next}")
        if(col EQUAL 16)
            string(APPEND text "\n")
            set(col 0)
        else()
            string(APPEND text " ")
        endif()
    endforeach()
    if(NOT col EQUAL 0)
        string(APPEND text "\n")
    endif()
    string(APPEND text "};\n")
    string(APPEND text "inline constexpr std::size_t k_${ident}_size = sizeof(k_${ident});\n\n")

    string(APPEND registry "    { \"${spv_base}\", k_${ident}, k_${ident}_size },\n")
endforeach()

string(APPEND text "struct ShaderBlob {\n")
string(APPEND text "    std::string_view name;\n")
string(APPEND text "    std::uint8_t const* data;\n")
string(APPEND text "    std::size_t size;\n")
string(APPEND text "};\n\n")

string(APPEND text "inline constexpr ShaderBlob k_shaders[] = {\n")
string(APPEND text "${registry}")
string(APPEND text "};\n\n")

string(APPEND text "inline ShaderBlob get(std::string_view name) {\n")
string(APPEND text "    for (ShaderBlob const& blob : k_shaders) {\n")
string(APPEND text "        if (blob.name == name) return blob;\n")
string(APPEND text "    }\n")
string(APPEND text "    return ShaderBlob{name, nullptr, 0};\n")
string(APPEND text "}\n\n")

string(APPEND text "} // namespace vulkan_runtime::shaders\n")

file(WRITE "${OUTPUT}" "${text}")
