#include "api/attention_causal_backward_api.h"
#include "core/vk_setup.h"
#include "embedded_shaders.hpp"
#include <array>
#include <cstdint>
#include <cstring>
#include <stdexcept>
namespace {
struct Buffer { vk::Buffer buffer{}; VmaAllocation allocation{nullptr}; };
Buffer make(VmaAllocator a, vk::DeviceSize s, vk::BufferUsageFlags u, VmaMemoryUsage m, VmaAllocationCreateFlags f=0) { VkBufferCreateInfo i{}; i.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO; i.size=s; i.usage=static_cast<VkBufferUsageFlags>(u); i.sharingMode=VK_SHARING_MODE_EXCLUSIVE; VmaAllocationCreateInfo x{}; x.usage=m; x.flags=f; VkBuffer b{}; VmaAllocation h{}; if(vmaCreateBuffer(a,&i,&x,&b,&h,nullptr)!=VK_SUCCESS) throw std::runtime_error("buffer"); return {vk::Buffer(b),h}; }
void drop(VmaAllocator a, Buffer& b) { if(b.allocation){vmaDestroyBuffer(a,static_cast<VkBuffer>(b.buffer),b.allocation);b.buffer=nullptr;b.allocation=nullptr;} }
struct PC { std::uint32_t tokens, hidden, mode; };
}
extern "C" int spaceslug_attention_causal_backward(float const* q,float const* k,float const* v,float const* dy,float* out,std::uint32_t t,std::uint32_t d,std::uint32_t mode) {
 if(!q||!k||!v||!dy||!out||!t||t>128||d!=64||mode>2)return 1;
 try {
  auto c=vulkan_runtime::core::create_context("attn-bwd"); vk::DeviceSize n=vk::DeviceSize(t)*d*sizeof(float);
  Buffer qb=make(c.allocator,n,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),kb=make(c.allocator,n,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),vb=make(c.allocator,n,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),db=make(c.allocator,n,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),ob=make(c.allocator,n,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferSrc,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE),st=make(c.allocator,n*6,vk::BufferUsageFlagBits::eTransferSrc|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_HOST,VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT);
  void* m{}; if(vmaMapMemory(c.allocator,st.allocation,&m)!=VK_SUCCESS)throw std::runtime_error("map"); auto* x=static_cast<char*>(m); std::memcpy(x,q,n);std::memcpy(x+n,k,n);std::memcpy(x+2*n,v,n);std::memcpy(x+3*n,dy,n);vmaFlushAllocation(c.allocator,st.allocation,0,4*n);vmaUnmapMemory(c.allocator,st.allocation);
  auto z=vulkan_runtime::shaders::get("attention_causal_backward.spv"); vk::ShaderModuleCreateInfo mi;mi.setCodeSize(z.size).setPCode(reinterpret_cast<std::uint32_t const*>(z.data));auto sm=c.device.createShaderModule(mi);std::array<vk::DescriptorSetLayoutBinding,5>bs{};for(std::uint32_t i=0;i<5;++i)bs[i].setBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setStageFlags(vk::ShaderStageFlagBits::eCompute);vk::DescriptorSetLayoutCreateInfo li;li.setBindings(bs);auto sl=c.device.createDescriptorSetLayout(li);vk::PushConstantRange p;p.setStageFlags(vk::ShaderStageFlagBits::eCompute).setOffset(0).setSize(sizeof(PC));vk::PipelineLayoutCreateInfo pli;pli.setSetLayouts(sl).setPushConstantRanges(p);auto pl=c.device.createPipelineLayout(pli);vk::PipelineShaderStageCreateInfo ss;ss.setStage(vk::ShaderStageFlagBits::eCompute).setModule(sm).setPName("main");vk::ComputePipelineCreateInfo ci;ci.setStage(ss).setLayout(pl);auto cr=c.device.createComputePipeline({},ci);if(cr.result!=vk::Result::eSuccess)throw std::runtime_error("pipeline");auto pipe=cr.value;
  vk::DescriptorPoolSize ps;ps.setType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(5);vk::DescriptorPoolCreateInfo dpi;dpi.setMaxSets(1).setPoolSizes(ps);auto pool=c.device.createDescriptorPool(dpi);vk::DescriptorSetAllocateInfo dai;dai.setDescriptorPool(pool).setSetLayouts(sl);auto set=c.device.allocateDescriptorSets(dai).front();std::array<vk::DescriptorBufferInfo,5>bi{};for(auto&i:bi)i.setOffset(0).setRange(VK_WHOLE_SIZE);bi[0].setBuffer(qb.buffer);bi[1].setBuffer(kb.buffer);bi[2].setBuffer(vb.buffer);bi[3].setBuffer(db.buffer);bi[4].setBuffer(ob.buffer);std::array<vk::WriteDescriptorSet,5>w{};for(std::uint32_t i=0;i<5;++i)w[i].setDstSet(set).setDstBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setBufferInfo(bi[i]);c.device.updateDescriptorSets(w,{});
  vk::CommandPoolCreateInfo cpi;cpi.setQueueFamilyIndex(c.computeQueueFamily);auto cp=c.device.createCommandPool(cpi);vk::CommandBufferAllocateInfo cai;cai.setCommandPool(cp).setLevel(vk::CommandBufferLevel::ePrimary).setCommandBufferCount(1);auto cmd=c.device.allocateCommandBuffers(cai).front();vk::CommandBufferBeginInfo begin{};cmd.begin(begin);for(auto const&it:std::array<std::pair<vk::DeviceSize,vk::Buffer>,4>{{{0,qb.buffer},{n,kb.buffer},{2*n,vb.buffer},{3*n,db.buffer}}}){vk::BufferCopy bc;bc.setSrcOffset(it.first).setDstOffset(0).setSize(n);cmd.copyBuffer(st.buffer,it.second,bc);}vk::MemoryBarrier ib;ib.setSrcAccessMask(vk::AccessFlagBits::eTransferWrite).setDstAccessMask(vk::AccessFlagBits::eShaderRead);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer,vk::PipelineStageFlagBits::eComputeShader,{},ib,{},{});cmd.bindPipeline(vk::PipelineBindPoint::eCompute,pipe);cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute,pl,0,set,{});PC pc{t,d,mode};cmd.pushConstants(pl,vk::ShaderStageFlagBits::eCompute,0,sizeof(pc),&pc);cmd.dispatch((t*d+255)/256,1,1);vk::MemoryBarrier obar;obar.setSrcAccessMask(vk::AccessFlagBits::eShaderWrite).setDstAccessMask(vk::AccessFlagBits::eTransferRead);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,vk::PipelineStageFlagBits::eTransfer,{},obar,{},{});vk::BufferCopy back;back.setSrcOffset(0).setDstOffset(4*n).setSize(n);cmd.copyBuffer(ob.buffer,st.buffer,back);cmd.end();vk::SubmitInfo si;si.setCommandBuffers(cmd);c.computeQueue.submit(si);c.computeQueue.waitIdle();if(vmaMapMemory(c.allocator,st.allocation,&m)!=VK_SUCCESS)throw std::runtime_error("map output");vmaInvalidateAllocation(c.allocator,st.allocation,4*n,n);std::memcpy(out,static_cast<char*>(m)+4*n,n);vmaUnmapMemory(c.allocator,st.allocation);
  c.device.destroyCommandPool(cp);c.device.destroyDescriptorPool(pool);c.device.destroyPipeline(pipe);c.device.destroyPipelineLayout(pl);c.device.destroyDescriptorSetLayout(sl);c.device.destroyShaderModule(sm);drop(c.allocator,st);drop(c.allocator,ob);drop(c.allocator,db);drop(c.allocator,vb);drop(c.allocator,kb);drop(c.allocator,qb);vulkan_runtime::core::destroy_context(c);return 0;
 } catch(...) { return 2; }
}
