#include "api/causal_loss_api.h"
#include "core/vk_setup.h"
#include "embedded_shaders.hpp"
#include <array>
#include <cstdint>
#include <cstring>
#include <stdexcept>

namespace {
struct Buffer { vk::Buffer buffer{}; VmaAllocation allocation{nullptr}; };
Buffer make_buffer(VmaAllocator allocator, vk::DeviceSize size, vk::BufferUsageFlags usage, VmaMemoryUsage memory, VmaAllocationCreateFlags flags = 0) {
    VkBufferCreateInfo info{}; info.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO; info.size = size; info.usage = static_cast<VkBufferUsageFlags>(usage); info.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    VmaAllocationCreateInfo ai{}; ai.usage = memory; ai.flags = flags; VkBuffer raw{}; VmaAllocation allocation{};
    if (vmaCreateBuffer(allocator, &info, &ai, &raw, &allocation, nullptr) != VK_SUCCESS) throw std::runtime_error("vmaCreateBuffer failed");
    return {vk::Buffer(raw), allocation};
}
void drop(VmaAllocator allocator, Buffer& buffer) { if (buffer.allocation) { vmaDestroyBuffer(allocator, static_cast<VkBuffer>(buffer.buffer), buffer.allocation); buffer.allocation = nullptr; } }
struct PC { std::uint32_t rows; std::uint32_t vocab; std::uint32_t logits_stride; };
}

extern "C" int spaceslug_causal_loss(float const* logits, std::uint32_t const* targets, std::uint32_t const* mask, float* dlogits, float* row_loss, std::uint32_t rows, std::uint32_t vocab) {
    if (!logits || !targets || !mask || !dlogits || !row_loss || rows == 0 || rows > 128 || vocab == 0 || vocab > 320) return 1;
    try {
        auto ctx = vulkan_runtime::core::create_context("spaceslug-causal-loss");
        vk::DeviceSize logits_bytes = vk::DeviceSize(rows) * vocab * sizeof(float), row_bytes = vk::DeviceSize(rows) * sizeof(float), target_bytes = row_bytes;
        Buffer logits_buf = make_buffer(ctx.allocator, logits_bytes, vk::BufferUsageFlagBits::eStorageBuffer | vk::BufferUsageFlagBits::eTransferDst, VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE);
        Buffer target_buf = make_buffer(ctx.allocator, target_bytes, vk::BufferUsageFlagBits::eStorageBuffer | vk::BufferUsageFlagBits::eTransferDst, VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE);
        Buffer mask_buf = make_buffer(ctx.allocator, target_bytes, vk::BufferUsageFlagBits::eStorageBuffer | vk::BufferUsageFlagBits::eTransferDst, VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE);
        Buffer grad_buf = make_buffer(ctx.allocator, logits_bytes, vk::BufferUsageFlagBits::eStorageBuffer | vk::BufferUsageFlagBits::eTransferSrc, VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE);
        Buffer loss_buf = make_buffer(ctx.allocator, row_bytes, vk::BufferUsageFlagBits::eStorageBuffer | vk::BufferUsageFlagBits::eTransferSrc, VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE);
        Buffer staging = make_buffer(ctx.allocator, logits_bytes * 2 + row_bytes * 4, vk::BufferUsageFlagBits::eTransferSrc | vk::BufferUsageFlagBits::eTransferDst, VMA_MEMORY_USAGE_AUTO_PREFER_HOST, VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT);
        void* mapped{}; if (vmaMapMemory(ctx.allocator, staging.allocation, &mapped) != VK_SUCCESS) throw std::runtime_error("vmaMapMemory failed"); auto* bytes = static_cast<char*>(mapped); std::memcpy(bytes, logits, logits_bytes); std::memcpy(bytes + logits_bytes, targets, target_bytes); std::memcpy(bytes + logits_bytes + target_bytes, mask, target_bytes); vmaUnmapMemory(ctx.allocator, staging.allocation); vmaFlushAllocation(ctx.allocator, staging.allocation, 0, logits_bytes + target_bytes * 2);
        auto blob = vulkan_runtime::shaders::get("causal_loss.spv"); vk::ShaderModuleCreateInfo mi; mi.setCodeSize(blob.size).setPCode(reinterpret_cast<std::uint32_t const*>(blob.data)); auto shader = ctx.device.createShaderModule(mi);
        std::array<vk::DescriptorSetLayoutBinding, 5> bindings{}; for (std::uint32_t i = 0; i < bindings.size(); ++i) bindings[i].setBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setStageFlags(vk::ShaderStageFlagBits::eCompute); vk::DescriptorSetLayoutCreateInfo li; li.setBindings(bindings); auto layout = ctx.device.createDescriptorSetLayout(li); vk::PushConstantRange pcr; pcr.setStageFlags(vk::ShaderStageFlagBits::eCompute).setOffset(0).setSize(sizeof(PC)); vk::PipelineLayoutCreateInfo pli; pli.setSetLayouts(layout).setPushConstantRanges(pcr); auto pipeline_layout = ctx.device.createPipelineLayout(pli);
        vk::PipelineShaderStageCreateInfo stage; stage.setStage(vk::ShaderStageFlagBits::eCompute).setModule(shader).setPName("main"); vk::ComputePipelineCreateInfo ci; ci.setStage(stage).setLayout(pipeline_layout); auto pipeline_result = ctx.device.createComputePipeline({}, ci); if (pipeline_result.result != vk::Result::eSuccess) throw std::runtime_error("createComputePipeline failed"); auto pipeline = pipeline_result.value;
        vk::DescriptorPoolSize ps; ps.setType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(5); vk::DescriptorPoolCreateInfo dpi; dpi.setMaxSets(1).setPoolSizes(ps); auto pool = ctx.device.createDescriptorPool(dpi); vk::DescriptorSetAllocateInfo dai; dai.setDescriptorPool(pool).setSetLayouts(layout); auto set = ctx.device.allocateDescriptorSets(dai).front(); std::array<vk::DescriptorBufferInfo, 5> infos{}; for (auto& info : infos) info.setOffset(0).setRange(VK_WHOLE_SIZE); infos[0].setBuffer(logits_buf.buffer); infos[1].setBuffer(target_buf.buffer); infos[2].setBuffer(mask_buf.buffer); infos[3].setBuffer(grad_buf.buffer); infos[4].setBuffer(loss_buf.buffer); std::array<vk::WriteDescriptorSet, 5> writes{}; for (std::uint32_t i = 0; i < writes.size(); ++i) writes[i].setDstSet(set).setDstBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setBufferInfo(infos[i]); ctx.device.updateDescriptorSets(writes, {});
        vk::CommandPoolCreateInfo cpi; cpi.setQueueFamilyIndex(ctx.computeQueueFamily); auto command_pool = ctx.device.createCommandPool(cpi); vk::CommandBufferAllocateInfo cai; cai.setCommandPool(command_pool).setLevel(vk::CommandBufferLevel::ePrimary).setCommandBufferCount(1); auto command = ctx.device.allocateCommandBuffers(cai).front(); vk::CommandBufferBeginInfo begin{}; command.begin(begin); for (auto const& source : std::array<std::pair<vk::DeviceSize, vk::Buffer>, 3>{{{0, logits_buf.buffer}, {logits_bytes, target_buf.buffer}, {logits_bytes + target_bytes, mask_buf.buffer}}}) { vk::BufferCopy copy; copy.setSrcOffset(source.first).setDstOffset(0).setSize(source.first == 0 ? logits_bytes : target_bytes); command.copyBuffer(staging.buffer, source.second, copy); } vk::MemoryBarrier input_barrier; input_barrier.setSrcAccessMask(vk::AccessFlagBits::eTransferWrite).setDstAccessMask(vk::AccessFlagBits::eShaderRead); command.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer, vk::PipelineStageFlagBits::eComputeShader, {}, input_barrier, {}, {}); command.bindPipeline(vk::PipelineBindPoint::eCompute, pipeline); command.bindDescriptorSets(vk::PipelineBindPoint::eCompute, pipeline_layout, 0, set, {}); PC pc{rows, vocab, vocab}; command.pushConstants(pipeline_layout, vk::ShaderStageFlagBits::eCompute, 0, sizeof(pc), &pc); command.dispatch(rows, 1, 1); vk::MemoryBarrier output_barrier; output_barrier.setSrcAccessMask(vk::AccessFlagBits::eShaderWrite).setDstAccessMask(vk::AccessFlagBits::eTransferRead); command.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader, vk::PipelineStageFlagBits::eTransfer, {}, output_barrier, {}, {}); vk::BufferCopy grad_copy; grad_copy.setSrcOffset(0).setDstOffset(logits_bytes + target_bytes * 2).setSize(logits_bytes); command.copyBuffer(grad_buf.buffer, staging.buffer, grad_copy); vk::BufferCopy loss_copy; loss_copy.setSrcOffset(0).setDstOffset(logits_bytes * 2 + target_bytes * 2).setSize(row_bytes); command.copyBuffer(loss_buf.buffer, staging.buffer, loss_copy); command.end(); vk::SubmitInfo submit; submit.setCommandBuffers(command); ctx.computeQueue.submit(submit); ctx.computeQueue.waitIdle(); if (vmaMapMemory(ctx.allocator, staging.allocation, &mapped) != VK_SUCCESS) throw std::runtime_error("vmaMapMemory failed"); vmaInvalidateAllocation(ctx.allocator, staging.allocation, logits_bytes + target_bytes * 2, logits_bytes + row_bytes); bytes = static_cast<char*>(mapped); std::memcpy(dlogits, bytes + logits_bytes + target_bytes * 2, logits_bytes); std::memcpy(row_loss, bytes + logits_bytes * 2 + target_bytes * 2, row_bytes); vmaUnmapMemory(ctx.allocator, staging.allocation);
        ctx.device.destroyCommandPool(command_pool); ctx.device.destroyDescriptorPool(pool); ctx.device.destroyPipeline(pipeline); ctx.device.destroyPipelineLayout(pipeline_layout); ctx.device.destroyDescriptorSetLayout(layout); ctx.device.destroyShaderModule(shader); drop(ctx.allocator, staging); drop(ctx.allocator, loss_buf); drop(ctx.allocator, grad_buf); drop(ctx.allocator, mask_buf); drop(ctx.allocator, target_buf); drop(ctx.allocator, logits_buf); vulkan_runtime::core::destroy_context(ctx); return 0;
    } catch (...) { return 2; }
}
