#include "api/output_projection_training_api.h"
#include "core/vk_setup.h"
#include "embedded_shaders.hpp"
#include "exec/engine.h"
#include <array>
#include <cstring>
#include <memory>
#include <stdexcept>

namespace outproj {
struct B { vk::Buffer b{}; VmaAllocation a{}; };
B make(VmaAllocator al, vk::DeviceSize n, vk::BufferUsageFlags usage, VmaMemoryUsage mem, VmaAllocationCreateFlags flags=0) {
    VkBufferCreateInfo ci{}; ci.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO; ci.size=n; ci.usage=static_cast<VkBufferUsageFlags>(usage); ci.sharingMode=VK_SHARING_MODE_EXCLUSIVE;
    VmaAllocationCreateInfo ai{}; ai.usage=mem; ai.flags=flags; VkBuffer b{}; VmaAllocation a{};
    if (vmaCreateBuffer(al,&ci,&ai,&b,&a,nullptr)!=VK_SUCCESS) {
        throw std::runtime_error("buffer");
    }
    return {vk::Buffer(b),a};
}
void drop(VmaAllocator al,B& b){if(b.a){vmaDestroyBuffer(al,static_cast<VkBuffer>(b.b),b.a);b={};}}
struct GradPC { std::uint32_t rows,tcap,hidden; };
struct SgdPC { std::uint32_t count; float lr; };
struct AdamPC { std::uint32_t count,step; float lr,b1,b2,eps,decay; };
vk::Pipeline pipe(vk::Device d,char const* name,vk::ShaderModule& sm,vk::DescriptorSetLayout sl,vk::PipelineLayout& pl,std::size_t pcs) {
    auto z=vulkan_runtime::shaders::get(name); vk::ShaderModuleCreateInfo mi; mi.setCodeSize(z.size).setPCode(reinterpret_cast<std::uint32_t const*>(z.data)); sm=d.createShaderModule(mi);
    vk::PushConstantRange pc; pc.setStageFlags(vk::ShaderStageFlagBits::eCompute).setSize(static_cast<std::uint32_t>(pcs)); vk::PipelineLayoutCreateInfo li; li.setSetLayouts(sl).setPushConstantRanges(pc); pl=d.createPipelineLayout(li);
    vk::PipelineShaderStageCreateInfo ss; ss.setStage(vk::ShaderStageFlagBits::eCompute).setModule(sm).setPName("main"); vk::ComputePipelineCreateInfo ci; ci.setStage(ss).setLayout(pl); auto r=d.createComputePipeline({},ci); if(r.result!=vk::Result::eSuccess) throw std::runtime_error("pipeline"); return r.value;
}
struct Graph {
    vulkan_runtime::core::VulkanContext c; std::unique_ptr<vulkan_runtime::exec::ExecEngine> e; std::uint32_t h,t; vk::DeviceSize wb,ab;
    B w,g,a,u,m,v,st; vk::ShaderModule gsh{},ssh{},ash{}; vk::DescriptorSetLayout gl{},sl{},al{}; vk::PipelineLayout gpl{},spl{},apl{}; vk::Pipeline gp{},sp{},ap{}; vk::DescriptorPool dp{}; vk::DescriptorSet gs{},ds{},as{}; std::uint64_t step_no=0;
    Graph(float const* in,std::uint32_t H,std::uint32_t T):c(vulkan_runtime::core::create_context("output-projection-training")),e(std::make_unique<vulkan_runtime::exec::ExecEngine>(c,3,1)),h(H),t(T),wb(vk::DeviceSize(H)*H*4),ab(vk::DeviceSize(T)*H*4),w(make(c.allocator,wb,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst|vk::BufferUsageFlagBits::eTransferSrc,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE)),g(make(c.allocator,wb,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferSrc,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE)),a(make(c.allocator,ab,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE)),u(make(c.allocator,ab,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE)),m(make(c.allocator,wb,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst|vk::BufferUsageFlagBits::eTransferSrc,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE)),v(make(c.allocator,wb,vk::BufferUsageFlagBits::eStorageBuffer|vk::BufferUsageFlagBits::eTransferDst|vk::BufferUsageFlagBits::eTransferSrc,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE)),st(make(c.allocator,2*ab+5*wb,vk::BufferUsageFlagBits::eTransferSrc|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_HOST,VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT)) {
        if(!in) {
            throw std::runtime_error("null weight");
        }
        void* x{};
        if(vmaMapMemory(c.allocator,st.a,&x)!=VK_SUCCESS) {
            throw std::runtime_error("map");
        }
        std::memcpy(static_cast<char*>(x)+2*ab,in,wb); vmaFlushAllocation(c.allocator,st.a,2*ab,wb); vmaUnmapMemory(c.allocator,st.a);
        auto layout=[&](std::uint32_t n){std::vector<vk::DescriptorSetLayoutBinding> b(n);for(std::uint32_t i=0;i<n;++i)b[i].setBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setStageFlags(vk::ShaderStageFlagBits::eCompute);vk::DescriptorSetLayoutCreateInfo q;q.setBindings(b);return c.device.createDescriptorSetLayout(q);};
        gl=layout(3);sl=layout(2);al=layout(4);gp=pipe(c.device,"output_projection_weight_grad.spv",gsh,gl,gpl,sizeof(GradPC));sp=pipe(c.device,"output_projection_sgd.spv",ssh,sl,spl,sizeof(SgdPC));ap=pipe(c.device,"output_projection_adamw.spv",ash,al,apl,sizeof(AdamPC));
        vk::DescriptorPoolSize ps;ps.setType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(9);vk::DescriptorPoolCreateInfo pi;pi.setMaxSets(3).setPoolSizes(ps);dp=c.device.createDescriptorPool(pi);std::array<vk::DescriptorSetLayout,3> layouts{gl,sl,al};vk::DescriptorSetAllocateInfo ai;ai.setDescriptorPool(dp).setSetLayouts(layouts);auto sets=c.device.allocateDescriptorSets(ai);gs=sets[0];ds=sets[1];as=sets[2];
        std::array<vk::DescriptorBufferInfo,9> bi{{{a.b,0,VK_WHOLE_SIZE},{u.b,0,VK_WHOLE_SIZE},{g.b,0,VK_WHOLE_SIZE},{w.b,0,VK_WHOLE_SIZE},{g.b,0,VK_WHOLE_SIZE},{w.b,0,VK_WHOLE_SIZE},{g.b,0,VK_WHOLE_SIZE},{m.b,0,VK_WHOLE_SIZE},{v.b,0,VK_WHOLE_SIZE}}};std::array<vk::WriteDescriptorSet,9> wr{};for(std::uint32_t i=0;i<3;++i)wr[i].setDstSet(gs).setDstBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setBufferInfo(bi[i]);for(std::uint32_t i=0;i<2;++i)wr[i+3].setDstSet(ds).setDstBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setBufferInfo(bi[i+3]);for(std::uint32_t i=0;i<4;++i)wr[i+5].setDstSet(as).setDstBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setBufferInfo(bi[i+5]);c.device.updateDescriptorSets(wr,{});
        auto q=e->submit([&](vk::CommandBuffer cmd){cmd.copyBuffer(st.b,w.b,vk::BufferCopy{2*ab,0,wb});cmd.fillBuffer(m.b,0,VK_WHOLE_SIZE,0);cmd.fillBuffer(v.b,0,VK_WHOLE_SIZE,0);});e->wait(q);
    }
    ~Graph(){e->drain();c.device.destroyDescriptorPool(dp);for(auto p:{ap,sp,gp})c.device.destroyPipeline(p);for(auto p:{apl,spl,gpl})c.device.destroyPipelineLayout(p);for(auto l:{al,sl,gl})c.device.destroyDescriptorSetLayout(l);for(auto s:{ash,ssh,gsh})c.device.destroyShaderModule(s);e.reset();drop(c.allocator,st);drop(c.allocator,v);drop(c.allocator,m);drop(c.allocator,u);drop(c.allocator,a);drop(c.allocator,g);drop(c.allocator,w);vulkan_runtime::core::destroy_context(c);}
    int run(float const* A,float const* U,std::uint32_t rows,float lr,bool adam,float b1,float b2,float eps,float decay){void*x{};if(vmaMapMemory(c.allocator,st.a,&x)!=VK_SUCCESS)return 2;std::memcpy(x,A,ab);std::memcpy(static_cast<char*>(x)+ab,U,ab);vmaFlushAllocation(c.allocator,st.a,0,2*ab);vmaUnmapMemory(c.allocator,st.a);if(adam){if(step_no==UINT64_MAX)return 1;++step_no;}auto q=e->submit([&](vk::CommandBuffer cmd){cmd.copyBuffer(st.b,a.b,vk::BufferCopy{0,0,ab});cmd.copyBuffer(st.b,u.b,vk::BufferCopy{ab,0,ab});vk::MemoryBarrier in;in.setSrcAccessMask(vk::AccessFlagBits::eTransferWrite).setDstAccessMask(vk::AccessFlagBits::eShaderRead);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer,vk::PipelineStageFlagBits::eComputeShader,{},in,{},{});cmd.bindPipeline(vk::PipelineBindPoint::eCompute,gp);cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute,gpl,0,gs,{});GradPC p{rows,t,h};cmd.pushConstants(gpl,vk::ShaderStageFlagBits::eCompute,0,sizeof(p),&p);cmd.dispatch((h*h+255)/256,1,1);vk::MemoryBarrier b;b.setSrcAccessMask(vk::AccessFlagBits::eShaderWrite).setDstAccessMask(vk::AccessFlagBits::eShaderRead);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,vk::PipelineStageFlagBits::eComputeShader,{},b,{},{});if(adam){cmd.bindPipeline(vk::PipelineBindPoint::eCompute,ap);cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute,apl,0,as,{});AdamPC p{h*h,static_cast<std::uint32_t>(step_no),lr,b1,b2,eps,decay};cmd.pushConstants(apl,vk::ShaderStageFlagBits::eCompute,0,sizeof(p),&p);}else{cmd.bindPipeline(vk::PipelineBindPoint::eCompute,sp);cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute,spl,0,ds,{});SgdPC p{h*h,lr};cmd.pushConstants(spl,vk::ShaderStageFlagBits::eCompute,0,sizeof(p),&p);}cmd.dispatch((h*h+255)/256,1,1);vk::MemoryBarrier out;out.setSrcAccessMask(vk::AccessFlagBits::eShaderWrite).setDstAccessMask(vk::AccessFlagBits::eTransferRead);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,vk::PipelineStageFlagBits::eTransfer,{},out,{},{});cmd.copyBuffer(w.b,st.b,vk::BufferCopy{0,2*ab+wb,wb});cmd.copyBuffer(g.b,st.b,vk::BufferCopy{0,2*ab+2*wb,wb});});e->wait(q);return 0;}
    int read(float*W,float*G){void*x{};if(vmaMapMemory(c.allocator,st.a,&x)!=VK_SUCCESS)return 2;vmaInvalidateAllocation(c.allocator,st.a,2*ab+wb,2*wb);std::memcpy(W,static_cast<char*>(x)+2*ab+wb,wb);std::memcpy(G,static_cast<char*>(x)+2*ab+2*wb,wb);vmaUnmapMemory(c.allocator,st.a);return 0;}
    int state(float*W,float*G,float*M,float*V,std::uint64_t*S){if(read(W,G)!=0)return 2;auto q=e->submit([&](vk::CommandBuffer cmd){vk::MemoryBarrier b;b.setSrcAccessMask(vk::AccessFlagBits::eShaderWrite).setDstAccessMask(vk::AccessFlagBits::eTransferRead);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,vk::PipelineStageFlagBits::eTransfer,{},b,{},{});cmd.copyBuffer(m.b,st.b,vk::BufferCopy{0,2*ab+3*wb,wb});cmd.copyBuffer(v.b,st.b,vk::BufferCopy{0,2*ab+4*wb,wb});});e->wait(q);void*x{};if(vmaMapMemory(c.allocator,st.a,&x)!=VK_SUCCESS)return 2;vmaInvalidateAllocation(c.allocator,st.a,2*ab+3*wb,2*wb);std::memcpy(M,static_cast<char*>(x)+2*ab+3*wb,wb);std::memcpy(V,static_cast<char*>(x)+2*ab+4*wb,wb);vmaUnmapMemory(c.allocator,st.a);*S=step_no;return 0;}
    int update_state(float const*W,float const*M,float const*V,std::uint64_t S){void*x{};if(vmaMapMemory(c.allocator,st.a,&x)!=VK_SUCCESS)return 2;auto base=2*ab;std::memcpy(static_cast<char*>(x)+base,W,wb);std::memcpy(static_cast<char*>(x)+base+3*wb,M,wb);std::memcpy(static_cast<char*>(x)+base+4*wb,V,wb);vmaFlushAllocation(c.allocator,st.a,base,5*wb);vmaUnmapMemory(c.allocator,st.a);auto q=e->submit([&](vk::CommandBuffer cmd){cmd.copyBuffer(st.b,w.b,vk::BufferCopy{base,0,wb});cmd.copyBuffer(st.b,m.b,vk::BufferCopy{base+3*wb,0,wb});cmd.copyBuffer(st.b,v.b,vk::BufferCopy{base+4*wb,0,wb});});e->wait(q);step_no=S;return 0;}
    int update(float const*W){void*x{};if(vmaMapMemory(c.allocator,st.a,&x)!=VK_SUCCESS)return 2;std::memcpy(static_cast<char*>(x)+2*ab,W,wb);vmaFlushAllocation(c.allocator,st.a,2*ab,wb);vmaUnmapMemory(c.allocator,st.a);auto q=e->submit([&](vk::CommandBuffer cmd){cmd.copyBuffer(st.b,w.b,vk::BufferCopy{2*ab,0,wb});});e->wait(q);return 0;}
};}
struct spaceslug_output_projection_training{outproj::Graph* g;};
extern "C" const char* spaceslug_output_projection_training_capability(){return "fp32_output_projection_only_sgd_adamw_standalone_caller_supplied_activations_no_tiny_graph_integration_no_qkv_integration";}
extern "C" spaceslug_output_projection_training* spaceslug_output_projection_training_create(float const*w,std::uint32_t h,std::uint32_t t){if(!w||!h||!t||h>4096||t>4096)return nullptr;try{return new spaceslug_output_projection_training{new outproj::Graph(w,h,t)};}catch(...){return nullptr;}}
extern "C" void spaceslug_output_projection_training_destroy(spaceslug_output_projection_training*x){if(x){delete x->g;delete x;}}
extern "C" int spaceslug_output_projection_training_step(spaceslug_output_projection_training*x,float const*a,float const*u,std::uint32_t r,float lr){return(!x||!x->g||!a||!u||r>x->g->t||!(lr>0.f))?1:x->g->run(a,u,r,lr,false,0,0,0,0);}
extern "C" int spaceslug_output_projection_training_adamw_step(spaceslug_output_projection_training*x,float const*a,float const*u,std::uint32_t r,float lr,float b1,float b2,float eps,float decay){return(!x||!x->g||!a||!u||r>x->g->t||!(lr>0.f)||!(b1>=0.f&&b1<1.f)||!(b2>=0.f&&b2<1.f)||!(eps>0.f))?1:x->g->run(a,u,r,lr,true,b1,b2,eps,decay);}
extern "C" int spaceslug_output_projection_training_readback_adamw_state(spaceslug_output_projection_training*x,float*w,float*g,float*m,float*v,std::uint64_t*s){return(!x||!x->g||!w||!g||!m||!v||!s)?1:x->g->state(w,g,m,v,s);}
extern "C" int spaceslug_output_projection_training_update_adamw_state(spaceslug_output_projection_training*x,float const*w,float const*m,float const*v,std::uint64_t s){return(!x||!x->g||!w||!m||!v)?1:x->g->update_state(w,m,v,s);}
extern "C" int spaceslug_output_projection_training_readback(spaceslug_output_projection_training*x,float*w,float*g){return(!x||!x->g||!w||!g)?1:x->g->read(w,g);}
extern "C" int spaceslug_output_projection_training_update(spaceslug_output_projection_training*x,float const*w){return(!x||!x->g||!w)?1:x->g->update(w);}
