#include "api/qkv_projection_training_api.h"
#include "core/vk_setup.h"
#include "embedded_shaders.hpp"
#include "exec/engine.h"
#include <array>
#include <cmath>
#include <cstring>
#include <memory>
#include <stdexcept>
namespace qkv {
struct B { vk::Buffer b{}; VmaAllocation a{}; };
B make(VmaAllocator a, vk::DeviceSize n, vk::BufferUsageFlags u, VmaMemoryUsage m, VmaAllocationCreateFlags f=0){ VkBufferCreateInfo i{}; i.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;i.size=n;i.usage=static_cast<VkBufferUsageFlags>(u);i.sharingMode=VK_SHARING_MODE_EXCLUSIVE;VmaAllocationCreateInfo x{};x.usage=m;x.flags=f;VkBuffer b{};VmaAllocation al{};if(vmaCreateBuffer(a,&i,&x,&b,&al,nullptr)!=VK_SUCCESS)throw std::runtime_error("buffer");return {vk::Buffer(b),al}; }
void drop(VmaAllocator a,B& b){if(b.a){vmaDestroyBuffer(a,static_cast<VkBuffer>(b.b),b.a);b={};}}
struct PC { std::uint32_t rows,tcap,hidden; float lr; };
struct Graph {
 vulkan_runtime::core::VulkanContext c; std::unique_ptr<vulkan_runtime::exec::ExecEngine> e; std::uint32_t h,t; vk::DeviceSize hb,ab; std::array<B,10> buf{}; B st{}; vk::ShaderModule sm{}; vk::DescriptorSetLayout sl{}; vk::PipelineLayout pl{}; vk::Pipeline p{}; vk::DescriptorPool dp{}; vk::DescriptorSet ds{};
 Graph(float const* q,float const* k,float const* v,std::uint32_t H,std::uint32_t T):c(vulkan_runtime::core::create_context("qkv-projection-training")),e(std::make_unique<vulkan_runtime::exec::ExecEngine>(c,3,1)),h(H),t(T),hb(vk::DeviceSize(H)*H*4),ab(vk::DeviceSize(T)*H*4){
  if(!q||!k||!v) throw std::runtime_error("null weight");
  auto su=vk::BufferUsageFlagBits::eStorageBuffer;
  auto dev=su|vk::BufferUsageFlagBits::eTransferDst|vk::BufferUsageFlagBits::eTransferSrc;
  for(int i=0;i<4;++i) buf[i]=make(c.allocator,ab,dev,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE);
  for(int i=4;i<10;++i) buf[i]=make(c.allocator,hb,dev,VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE);
  st=make(c.allocator,4*ab+6*hb+6*hb,vk::BufferUsageFlagBits::eTransferSrc|vk::BufferUsageFlagBits::eTransferDst,VMA_MEMORY_USAGE_AUTO_PREFER_HOST,VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT);
  void*m{};if(vmaMapMemory(c.allocator,st.a,&m)!=VK_SUCCESS)throw std::runtime_error("map");std::memcpy(static_cast<char*>(m)+4*ab+0*hb,q,hb);std::memcpy(static_cast<char*>(m)+4*ab+1*hb,k,hb);std::memcpy(static_cast<char*>(m)+4*ab+2*hb,v,hb);vmaFlushAllocation(c.allocator,st.a,4*ab,3*hb);vmaUnmapMemory(c.allocator,st.a);
  std::array<vk::DescriptorSetLayoutBinding,10> bs{};for(std::uint32_t i=0;i<10;++i)bs[i].setBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setStageFlags(vk::ShaderStageFlagBits::eCompute);vk::DescriptorSetLayoutCreateInfo li;li.setBindings(bs);sl=c.device.createDescriptorSetLayout(li);auto z=vulkan_runtime::shaders::get("qkv_projection_grad.spv");vk::ShaderModuleCreateInfo mi;mi.setCodeSize(z.size).setPCode(reinterpret_cast<std::uint32_t const*>(z.data));sm=c.device.createShaderModule(mi);vk::PushConstantRange pc;pc.setStageFlags(vk::ShaderStageFlagBits::eCompute).setSize(sizeof(PC));vk::PipelineLayoutCreateInfo pli;pli.setSetLayouts(sl).setPushConstantRanges(pc);pl=c.device.createPipelineLayout(pli);vk::PipelineShaderStageCreateInfo ss;ss.setStage(vk::ShaderStageFlagBits::eCompute).setModule(sm).setPName("main");vk::ComputePipelineCreateInfo ci;ci.setStage(ss).setLayout(pl);auto pr=c.device.createComputePipeline({},ci);if(pr.result!=vk::Result::eSuccess)throw std::runtime_error("pipeline");p=pr.value;vk::DescriptorPoolSize ps;ps.setType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(10);vk::DescriptorPoolCreateInfo dpi;dpi.setMaxSets(1).setPoolSizes(ps);dp=c.device.createDescriptorPool(dpi);vk::DescriptorSetAllocateInfo dai;dai.setDescriptorPool(dp).setSetLayouts(sl);ds=c.device.allocateDescriptorSets(dai)[0];std::array<vk::DescriptorBufferInfo,10> bi{};for(std::uint32_t i=0;i<10;++i)bi[i]=vk::DescriptorBufferInfo{buf[i].b,0,VK_WHOLE_SIZE};std::array<vk::WriteDescriptorSet,10> wr{};for(std::uint32_t i=0;i<10;++i)wr[i].setDstSet(ds).setDstBinding(i).setDescriptorType(vk::DescriptorType::eStorageBuffer).setDescriptorCount(1).setBufferInfo(bi[i]);c.device.updateDescriptorSets(wr,{});
  auto id=e->submit([&](vk::CommandBuffer cmd){for(int i=0;i<3;++i){vk::BufferCopy cp;cp.setSrcOffset(4*ab+i*hb).setDstOffset(0).setSize(hb);cmd.copyBuffer(st.b,buf[4+i].b,cp);}});e->wait(id);
 }
 ~Graph(){e->drain();c.device.destroyDescriptorPool(dp);c.device.destroyPipeline(p);c.device.destroyPipelineLayout(pl);c.device.destroyDescriptorSetLayout(sl);c.device.destroyShaderModule(sm);e.reset();drop(c.allocator,st);for(auto&b:buf)drop(c.allocator,b);vulkan_runtime::core::destroy_context(c);}
 int step(float const*x,float const*dq,float const*dk,float const*dv,std::uint32_t rows,float lr){void*m{};if(vmaMapMemory(c.allocator,st.a,&m)!=VK_SUCCESS)return 2;std::memcpy(m,x,ab);std::memcpy(static_cast<char*>(m)+ab,dq,ab);std::memcpy(static_cast<char*>(m)+2*ab,dk,ab);std::memcpy(static_cast<char*>(m)+3*ab,dv,ab);vmaFlushAllocation(c.allocator,st.a,0,4*ab);vmaUnmapMemory(c.allocator,st.a);auto id=e->submit([&](vk::CommandBuffer cmd){for(int i=0;i<4;++i){vk::BufferCopy cp;cp.setSrcOffset(i*ab).setDstOffset(0).setSize(ab);cmd.copyBuffer(st.b,buf[i].b,cp);}vk::MemoryBarrier ib;ib.setSrcAccessMask(vk::AccessFlagBits::eTransferWrite).setDstAccessMask(vk::AccessFlagBits::eShaderRead);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer,vk::PipelineStageFlagBits::eComputeShader,{},ib,{},{});cmd.bindPipeline(vk::PipelineBindPoint::eCompute,p);cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute,pl,0,ds,{});PC pc{rows,t,h,lr};cmd.pushConstants(pl,vk::ShaderStageFlagBits::eCompute,0,sizeof(pc),&pc);cmd.dispatch((3*h*h+255)/256,1,1);vk::MemoryBarrier ob;ob.setSrcAccessMask(vk::AccessFlagBits::eShaderWrite).setDstAccessMask(vk::AccessFlagBits::eTransferRead);cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,vk::PipelineStageFlagBits::eTransfer,{},ob,{},{});for(int i=0;i<6;++i){vk::BufferCopy cp;cp.setSrcOffset(0).setDstOffset(4*ab+i*hb).setSize(hb);cmd.copyBuffer(buf[i+4].b,st.b,cp);}});e->wait(id);return 0;}
 int read(float*q,float*k,float*v,float*gq,float*gk,float*gv){void*m{};if(vmaMapMemory(c.allocator,st.a,&m)!=VK_SUCCESS)return 2;vmaInvalidateAllocation(c.allocator,st.a,4*ab,6*hb);for(int i=0;i<6;++i)std::memcpy((i==0?q:i==1?k:i==2?v:i==3?gq:i==4?gk:gv),static_cast<char*>(m)+4*ab+i*hb,hb);vmaUnmapMemory(c.allocator,st.a);return 0;}
};}
struct spaceslug_qkv_projection_training{qkv::Graph*g;};
extern "C" const char* spaceslug_qkv_projection_training_capability(){return "fp32_qkv_projection_gradient_sgd_standalone_deterministic_row_major_HH_no_tiny_graph_integration";}
extern "C" spaceslug_qkv_projection_training* spaceslug_qkv_projection_training_create(float const*q,float const*k,float const*v,std::uint32_t h,std::uint32_t t){if(!q||!k||!v||!h||!t||h>4096||t>4096)return nullptr;try{return new spaceslug_qkv_projection_training{new qkv::Graph(q,k,v,h,t)};}catch(...){return nullptr;}}
extern "C" void spaceslug_qkv_projection_training_destroy(spaceslug_qkv_projection_training*x){if(x){delete x->g;delete x;}}
extern "C" int spaceslug_qkv_projection_training_step(spaceslug_qkv_projection_training*x,float const*s,float const*q,float const*k,float const*v,std::uint32_t r,float lr){return(!x||!x->g||!s||!q||!k||!v||r>x->g->t||!std::isfinite(lr)||!(lr>0.f))?1:x->g->step(s,q,k,v,r,lr);}
extern "C" int spaceslug_qkv_projection_training_readback(spaceslug_qkv_projection_training*x,float*q,float*k,float*v,float*gq,float*gk,float*gv){return(!x||!x->g||!q||!k||!v||!gq||!gk||!gv)?1:x->g->read(q,k,v,gq,gk,gv);}
